version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: quadro_postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quadro_soci
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: quadro_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
